### ISSUE TITLE
Ability to send email for lost password ?

### ISSUE THREAD

**Issue by mfaure** [benjamin-heasly/archiva-docker#1]
Hi,

I've played with the Docker image (cool !) and was unable to send any email (typically for a lost password).

Is the image able to send email ? Did I miss something ?

Thank you

**Comment by benjamin-heasly** [comment]
Thanks!

Agree email is important for passwords and stuff.

I don't think we can configure email once and for all inside this docker image, since it requires server config and credentials.  The mail server should probably live out on the Internet somewhere, or at least in a different Docker image.

But I think you can mount in the necessary config when running this image.  I'm using [gmail's free smpt service](https://support.google.com/a/answer/176600?hl=en) for one project, and the config looks like this:

`/var/archiva/conf/jetty.xml`

```
  <New id="validation_mail" class="org.eclipse.jetty.plus.jndi.Resource">
    <Arg>mail/Session</Arg>
    <Arg>
      <New class="org.eclipse.jetty.jndi.factories.MailSessionReference">
        <Set name="user">***</Set>
        <Set name="password">***</Set>
        <Set name="properties">
          <New class="java.util.Properties">
            <Put name="mail.user">***</Put>
            <Put name="mail.password">***</Put>
            <Put name="mail.smtp.host">smtp.gmail.com</Put>
            <Put name="mail.transport.protocol">smtp</Put>
            <Put name="mail.smtp.port">587</Put>
            <Put name="mail.smtp.auth">true</Put>
            <Put name="mail.smtp.starttls.enable">true</Put>
            <Put name="mail.debug">true</Put>
          </New>
        </Set>
      </New>
    </Arg>
  </New>
```

This makes an email resource available in the Jetty container.  Archiva knows how to find it from there.

**Comment by mfaure** [comment]
Great, thanks !

Your excerpt would be a great help in the README for other users

**Comment by benjamin-heasly** [comment]
Agree again.  Already put it there!  Thanks.
